# Generated by Django 2.2.10 on 2020-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_disfraces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
