# Generated by Django 2.2.10 on 2020-03-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_disfraces', '0003_producto_imgen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imgen',
        ),
    ]
