# Generated by Django 2.2.10 on 2020-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_disfraces', '0004_remove_producto_imgen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
